### PR TITLE
WPLS/PLSX pair added to fetch PLSX price

### PR DESCRIPTION
**Pull request by ShintoSan**
Added another pair of WPLS/PLSX to fetch PLSX price. Now using the weighted average of DAI/PLSX and WPLS/PLSX

### Checklist

This pull request is:

- [ ] A documentation error, docs update, or typographical error fix
	- No tests or issue needed
- [ ] A code fix
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a bug report issue 
	- Please include tests. Fixes without tests will not be accepted unless it's related to the documentation only.
    - Please make sure docs are updated if need be
- [ ] A feature implementation
	- Please reference the related issue by including "Closes `<link to issue>`" in this Pull Request's summary section. 
        - If no issue exists, please create a feature enhancement issue 
	- Please include tests
    - Please make sure docs updates are both thorough and easy to reproduce by somebody with limited knowledge of the feature that you are submitting

**Happy engineering!**

### CODE REVIEW

**Review by jensendarren — APPROVED** [review]
@dsm-ll PR looks good to me can you also review please?

**Comment by jensendarren** [comment]
@emozilla can you review this PR please?

**Comment by jensendarren** [comment]
@ShintoSan Thank you for submitting this PR! One thing I want to bring to your attention is that we are now also applying a TWAP in addition to the VWAP. Its worth considering this in your PR and you can take a look at our [TWAP PR here](https://github.com/fetchoracle/telliot-feeds/pull/58) for more details. Feel free to reach out if you have any questions.

**Review by dsm-ll — APPROVED** [review]
The price is reporting correctly. The only comment that I have is that the usage of WPLS/DAI as the only source for the price of PLS could be risky since if this liquidity pool were compromised the price of PLSX would be compromised as well. Please consider using more than one source for the price of PLS to calculate the price of PLSX.

**Comment by jensendarren** [comment]
@ShintoSan I am merging this PR into our `dev` branch now. However, please consider the comments we have shared with you here.

**Pull request merged**
